config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  resources :posts do
    member do
      get 'like',   to: 'posts#like',   as: 'like'
      get 'unlike', to: 'posts#unlike', as: 'unlike'
    end
    resources :comments,module: :posts
  end

  resources :blogs do
    resources :articles do
      member do
        get 'upvote', to: 'articles#upvote', as: 'upvote'
        get 'downvote', to: 'articles#downvote', as: 'downvote'
      end
      
    end
    member do
      get 'subscribe',   to: 'blogs#subscribe',   as: 'subscribe'
      get 'unsubscribe', to: 'blogs#unsubscribe', as: 'unsubscribe'
    end
  end

  resources :articles do
    resources :comments,module: :articles
  end

  get 'checkNotification',to: 'notifications#checkCounter',as: 'notification'         #Check notification with AJAX
  get 'i/notifications',to: 'notifications#notifications',as: 'all_notifications'     #Get User's notifications
  delete 'i/notifications/:id/destroy',to: 'notifications#destroy',as: 'delete_notification'      #Delete users notification  000

  get 'users/:username/followers',to: 'pages#followers',as: 'followers'               #Get Users's Followers
  get 'users/:username/followings',to: 'pages#followings',as: 'followings'            #Get Users's Followees

  get 'gettingStarted/1',to: 'informations#bio',as: 'add_bio'
  get 'gettingStarted/2',to: 'informations#interests',as: 'add_interests'
  get 'gettingStarted/3',to: 'informations#avatar',as: 'add_bio_s'
  patch 'gettingStarted/1',to: 'informations#updateBio',as: 'save_bio'

  match 'i/explore',to: 'pages#explore', as: 'explore',via: [:get,:post]
  post 'i/search',to: 'pages#lala',as: 'do_search'
  get 'i/fetch',to: 'pages#fetch', as: 'fetch'
  patch 'i/updateAvatar',to: 'pages#updateAvatar', as: 'update_avatar'
  patch 'i/blogs/:id/updateAvatar',to: 'blogs#updateAvatar', as: 'update_blog_avatar'
  
  get 'dashboard',to: 'pages#dashboard',as: 'dashboard'
  get ':link',to: 'blogs#show', as: 'page'
  get ':link/subscribers',to: 'blogs#getSubscribers', as: 'get_subscribers'
  
  get ':id/follow',to: 'blogs#follow',as: 'follow_user'
  get ':id/unfollow',to: 'blogs#unfollow',as: 'unfollow_user'
  

  get 'users/:username',    to: 'pages#sketchbook', as: 'sketchbook'
  # get 'userCard/:username', to: 'pages#userCard',   as: 'userCard'
  

  post 'blogs/check_availability',to: 'pages#checkData',as: 'checkData'
  post 'users/check_availability',to: 'pages#checkUsername',as: 'checkUsername'
  
  root 'pages#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :articles
  acts_as_followable
  has_attached_file :avatar, :styles => { :large => "128x128#",:medium => "73x73#",:small => "48x48#" ,:thumb => "24x24#" }, :default_url => "/images/:style/default.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :name,:desc,:link, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include ActionView::Helpers::UrlHelper
  before_action :authenticate_user!, except: [:show,:index]

  def index
    # Display Most Popular Blogs
  end

  def show
    @blog = Blog.where('link == ?',params[:link]).first
    if @blog.nil?
      redirect_to root_path, :notice => 'BLOG NOT FOUND'
    else
      @articles = Article.where("blog_id == ?",@blog.id)
    end
  end

  def new
    @blog = Blog.new
  end

  # def blogSuggestions
  #   @blogs = []
  #   @communities = []
    
  #   @blogs = Blog.where('community_id')
  # end

  def fetchArticles
    @blog = Blog.where('name == ?',params[:link])
    @articles = Article.where('blog_id == ?',@blog.id).where('').order(created_at: :desc).limit(2)
    respond_to do |format|
      format.js
    end
  end

  def checkUniqueLink
    @link = Blog.where('link == ?',params[:link]).first
    if /\W/.match(params[:link]).nil?
      if @link.nil?
        respond_to do |format|
          format.html{redirect_to :back}
          format.js{@data = 'Link available'}
        end
      else
        respond_to do |format|
          format.html{redirect_to :back}
          format.js{@data = 'Not available'}
        end
      end
    else
      respond_to do |format|
        format.html{redirect_to :back}
        format.js{@data = 'Only Characters and Numbers'}
      end
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      respond_to do |format|
        format.html{redirect_to blog_path(@blog)}
        format.js{}
      end
    else
      render 'new'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
    if @blog
      if @blog.user_id != current_user.id
        redirect_to :back, :notice => "Unauthorized Action"
      end
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog
      if @blog.user_id != current_user.id
        redirect_to :back, :notice => "Unauthorized Action"
      else
        @blog.update(blog_params)
        respond_to do |format|
          format.html{ redirect_to blog_path(@blog)}
          format.js
        end
      end
    end
  end

  def updateAvatar
    @blog = Blog.find(params[:id])
    if @blog
      @blog.update_attributes(avatar: params[:blog][:avatar])
      @blog.save
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
    if @blog.user_id != current_user.id
      redirect_to :back, :notice => "Unauthorized Action"
    else
      @blog = Blog.find(params[:id])
      @blog.destroy
      respond_to do |format|
        format.html{redirect_to :back}
        format.js{}
      end
    end
  end

  def subscribe
    @blog = Blog.find(params[:id])
    if !@blog.nil?
      if !current_user.follows?(@blog)
        current_user.follow!(@blog)
        respond_to do |format|
          format.html{redirect_to :back}
          format.js{}
        end
      end
    end
  end

  def unsubscribe
    @blog = Blog.find(params[:id])
    if !@blog.nil?
      if current_user.follows?(@blog)
        current_user.unfollow!(@blog)
        respond_to do |format|
          format.html{redirect_to :back}
          format.js{}
        end
      end
    end
  end

  def getSubscribers
    @blog = Blog.where('link == ?',params[:link]).first
    if @blog
      @followers = Follow.where('followable_type == ?',"Blog").where('followable_id == ?',@blog.id).pluck('follower_id')
      if @followers
        @users ||=[]
        @followers.each do |follower|
          @users << User.find(follower)
        end
      end 
    end
  end

  # To Be moved to Seperate Controller

  def follow
    @user = User.find(params[:id])
    if !@user.nil?
      if !current_user.follows?(@user)
        current_user.follow!(@user)
        @notice = Notification.new
        @notice.user_id = @user.id
        @notice.notice = link_to current_user.username, sketchbook_path(username: current_user.username) "is following you"
        @notice.trigger_type = "Follow"
        @notice.trigger_user_id = current_user.id
        @notice.save!
        respond_to do |format|
          format.html{redirect_to :back}
          format.js {render layout: false}
        end
      end
    end
  end

  def unfollow
    @user = User.find(params[:id])
    if !@user.nil?
      if current_user.follows?(@user)
        current_user.unfollow!(@user)
        @notice = Notification.where(user_id: @user.id).where(trigger_type: "Follow").where(trigger_user_id: current_user.id).first
        if !@notice.nil? 
          @notice.destroy
        end
        respond_to do |format|
          format.html{redirect_to :back}
          format.js {render layout: false}
        end
      end
    end
  end



  private
    def blog_params
      params.require(:blog).permit(:name,:desc,:category_id,:link)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.haml
= simple_form_for(@blog,html: {multipart: true,class: 'blog-form'}, :validate => true) do |f|
  = f.error_notification
  .form-group
    = f.input :name,label: false,input_html:{placeholder: "NAME YOUR BLOG"}
  .form-group
    = f.input :desc,label: false,input_html:{placeholder: 'Short Bio about your blog'}
  .form-group
    = f.association :category
  .form-group
    %span http://innfact.com/
    %span= f.input :link,label: false,input_html:{placeholder: 'CHOOSE A URL',onBlur: "checkAvailability()"}
    %span#user-availability-status.pull-right{style: 'display:none;'}
  .form-actions
    = f.submit "Create",class: 'btn btn-warning'

app/views/blogs/checkData.js.erb
$('#user-availability-status').html(<%= data %>);

app/views/blogs/checkUniqueLink.js.erb
$('input[type="text"]').value('<%= @data %>');

app/views/blogs/edit.html.haml
.row
	.col-md-3{style: 'text-align:center;'}
		= image_tag(@blog.avatar.url(:large),class: 'img-thumbnail',style: 'display:block;margin-left:auto;margin-right:auto;width:auto;')
		%h4= link_to @blog.name.capitalize,page_path(link: @blog.link)
	.col-md-6{style: 'border-left:3px solid #e9e9e9;'}
		%h3 Control Panel
		%hr		
		= simple_form_for(@blog,html: {multipart: true,class: 'blog-form'}) do |f|
			.form-group
				= f.input :name,label: "Name",input_html:{placeholder: "NAME YOUR BLOG"}
			.form-group
				= f.input :desc,label: "Description",input_html:{placeholder: 'Short Bio about your blog'}
			.form-group
				= f.association :category
			.form-group
				%span 
					%label Link
				%br
				%span http://innfact.com/
				%span= f.input :link,label: false,input_html:{placeholder: 'CHOOSE A URL',onBlur: "checkAvailability()"}
				%span#user-availability-status.pull-right{style: 'display:none;margin: 1rem 0;'}
			.form-actions
				= f.submit "Update Blog",class: 'btn btn-warning',style: 'width:100%;text-align:center;line-height:2;'

app/views/blogs/follow.js.erb
$("a.btn-follow[data-id = <%= @user.id %>]").removeClass('btn-follow').addClass('btn-unfollow').text('Following').attr('href','<%= unfollow_user_path(@user.id) %>');

app/views/blogs/getSubscribers.html.haml
- if !@users.empty?
	%h3 Subscribers
	= render partial: 'pages/user',collection: @users
- else
	#Empty{style: 'width:100%;color:#989898;text-align:center;font-size:1.6em;margin-top:10rem;'}
		NOTHING FOUND HERE

app/views/blogs/new.html.haml
.row
	.col-md-6{style: 'border-right:3px solid #e9e9e9;'}
		%h3 Create Blog
		%hr
		= render partial: 'form'
	.col-md-6
		%h3 Important Points
		%hr
		%ul.guidlines
			%li Creating a blog is the best way to share the information and knowledge with the community.
			%li Always Share only relavent information on your blog and maintain the quality of the content and hence of site. 
			%li Each Blog Post is votable and gets automatically deleted if is not received well by the community.

			

app/views/blogs/show.html.haml
.row#body{style: 'margin-top:3rem;'}
  .col-md-3.hidden-sm.hidden-xs{style: 'text-align:center;'}
    .blogAvatar{style: 'position:relative;'}
      = image_tag(@blog.avatar.url(:large),class: 'img-rounded',id: 'blogAvatar',style: 'border: 1px solid #e9e9e9;position:relative;',data:{toggle: "tooltip",placement: "top", title: "#{@blog.name.capitalize}"})
      - if user_signed_in? and @blog.user.username == current_user.username
        %span= link_to fa_icon('camera lg'),'#',remote: true,onclick: "update_blog_avatar(#{@blog.id})",id: 'update-blog-avatar-trigger',class: 'update-avatar-trigger',data:{toggle: "tooltip",placement: "bottom", title: "Change Avatar"}
        = form_for @blog,url: update_blog_avatar_path(@blog.id), html:{remote: true,class: 'update-avatar',method: :patch,multipart: true} do |f|
          = f.file_field :avatar
          = f.submit "Upload"
    %h4= link_to @blog.name.capitalize
    %table.table{style: 'margin-top:3rem;'}
      %tr 
        %td 
          %b Category
        %td= @blog.category.name
      %tr
        %td 
          %b From
        %td= fa_icon('map-marker',text: "India")
      %tr  
        %td 
          %b Started
        %td= fa_icon('clock-o',text:"Jan 2015")

  .col-md-6{style: 'border-left:2px solid #e9e9e9;min-height:100vh;border-right:2px solid #e9e9e9;'}
    - if @articles.blank?
      .EmptyDiv{style: 'text-align:center;color:#989898;font-size:1.1em;'}
        - if user_signed_in? and @blog.user.username==current_user.username
          %h4
            #{fa_icon('frown-o lg')} Nothing to show here  
          = link_to "Compose Post",new_blog_article_path(@blog),style: {color: '#989898'}
        - else
          %h4
            #{fa_icon('frown-o lg')} Nothing to show here 
    - else
      .Posts#Posts{style: 'width:90%;margin-left:auto;margin-right:auto;margin-top:-2rem;'}
        .InFo{style: 'display:block;background-color:#ffffff;box-shadow:0 0 3px 1px #efeeee;padding:1rem;text-transform:uppercase;'}
          .FoLlowers{style: 'text-align:center;display:inline-block;width:49%;'}
            = link_to pluralize(@blog.followers(User).count,"Subscriber"),get_subscribers_path(link: @blog.link),data:{toggle: "tooltip",placement: "bottom", title: "Followers"}
          .ArticleCounter{style: 'text-align:center;display:inline-block;width:49%;'}
            = link_to pluralize(@blog.articles.count,"Article"),'#',data:{toggle: "tooltip",placement: "bottom", title: "Articles"}
        = render partial: 'articles/article',collection: @articles
        #loader
          #anime
        = link_to "Load More Posts",'#',remote: true,class: 'load-more',data:{id: @blog.name}
  .col-md-3.hidden-sm.hidden-xs
    .Follow-field{style: 'margin-bottom:3rem;'}
      - if user_signed_in?
        - if current_user.follows?(@blog) and current_user.id != @blog.user.id
          = link_to "Following",unsubscribe_blog_path(@blog.id),class: 'btn btn-unfollow'
        - elsif !current_user.follows?(@blog) and current_user.id != @blog.user.id
          = link_to "Follow",subscribe_blog_path(@blog.id),class: 'btn btn-follow'
        - elsif @blog.user.id == current_user.id
          = link_to "New Post",new_blog_article_path(@blog),class: 'new-post-btn',data:{toggle: "tooltip",placement: "bottom", title: "Compose Post"}
          %br
          = link_to "Control Panel",edit_blog_path(@blog),class: 'btn',data:{toggle: "tooltip",placement: "bottom", title: "Control Panel"},style: 'line-height: 2;width:100%;text-align:center;display:block;background-color:#d9534f;color:#ffffff;border-radius:0px;'
      - else
        = link_to "Sign Up To Follow",new_user_registration_path,class: 'btn btn-warning',style: 'width:100%;display:block;text-align:center;'
        %br
        %br
        = link_to "Post to Author",new_user_registration_path,class: 'btn btn-info',style: 'width:100%;display:block;text-align:center;'

app/views/blogs/unfollow.js.erb
$("a.btn-unfollow[data-id = <%= @user.id %>]").removeClass('btn-unfollow').addClass('btn-follow').text('Follow').attr('href','<%= follow_user_path(@user.id) %>');
// alert("HELLo");

app/views/blogs/updateAvatar.js.erb
$('img[id = blogAvatar]').attr('src','<%= @blog.avatar.url(:large) %>');