config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  resources :posts do
    member do
      get 'like',   to: 'posts#like',   as: 'like'
      get 'unlike', to: 'posts#unlike', as: 'unlike'
    end
    resources :comments,module: :posts
  end

  resources :blogs do
    resources :articles do
      member do
        get 'upvote', to: 'articles#upvote', as: 'upvote'
        get 'downvote', to: 'articles#downvote', as: 'downvote'
      end
      
    end
    member do
      get 'subscribe',   to: 'blogs#subscribe',   as: 'subscribe'
      get 'unsubscribe', to: 'blogs#unsubscribe', as: 'unsubscribe'
    end
  end

  resources :articles do
    resources :comments,module: :articles
  end

  get 'checkNotification',to: 'notifications#checkCounter',as: 'notification'         #Check notification with AJAX
  get 'i/notifications',to: 'notifications#notifications',as: 'all_notifications'     #Get User's notifications
  delete 'i/notifications/:id/destroy',to: 'notifications#destroy',as: 'delete_notification'      #Delete users notification  000

  get 'users/:username/followers',to: 'pages#followers',as: 'followers'               #Get Users's Followers
  get 'users/:username/followings',to: 'pages#followings',as: 'followings'            #Get Users's Followees

  get 'gettingStarted/1',to: 'informations#bio',as: 'add_bio'
  get 'gettingStarted/2',to: 'informations#interests',as: 'add_interests'
  get 'gettingStarted/3',to: 'informations#avatar',as: 'add_bio_s'
  patch 'gettingStarted/1',to: 'informations#updateBio',as: 'save_bio'

  match 'i/explore',to: 'pages#explore', as: 'explore',via: [:get,:post]
  post 'i/search',to: 'pages#lala',as: 'do_search'
  get 'i/fetch',to: 'pages#fetch', as: 'fetch'
  patch 'i/updateAvatar',to: 'pages#updateAvatar', as: 'update_avatar'
  patch 'i/blogs/:id/updateAvatar',to: 'blogs#updateAvatar', as: 'update_blog_avatar'
  
  get 'dashboard',to: 'pages#dashboard',as: 'dashboard'
  get ':link',to: 'blogs#show', as: 'page'
  get ':link/subscribers',to: 'blogs#getSubscribers', as: 'get_subscribers'
  
  get ':id/follow',to: 'blogs#follow',as: 'follow_user'
  get ':id/unfollow',to: 'blogs#unfollow',as: 'unfollow_user'
  

  get 'users/:username',    to: 'pages#sketchbook', as: 'sketchbook'
  # get 'userCard/:username', to: 'pages#userCard',   as: 'userCard'
  

  post 'blogs/check_availability',to: 'pages#checkData',as: 'checkData'
  post 'users/check_availability',to: 'pages#checkUsername',as: 'checkUsername'
  
  root 'pages#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :blog
	has_many :comments,as: :commentable
	acts_as_votable
	has_attached_file :image, :styles => { :large => "500x500>",:medium => "400x400>",:small => "48x48#"}, :default_url => "/images/:style/default.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :title,:content,presence: true
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < CommentsController
	before_action :set_commentable

	private
		def set_commentable
			@commentable = Article.find(params[:article_id])
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show]
	before_action :set_article,except: [:new,:create]
	before_action :set_blog,only: [:new,:create]
	
	def show
	end
	
	def new
		@article = Article.new
	end

	def create
		if @blog.user_id == current_user.id
			@article = Article.new(article_params)
			@article.blog_id = @blog.id
			if @article.save
				respond_to do |format|
					format.html{redirect_to blog_path(@blog)}
				end
			else
				render 'new'
			end
		else
			redirect_to root_path,flash[:notice]=> "Unauthorized action"
		end
	end

	def edit
	end

	def update
	end

	def destroy
		if @article.blog.user.id = current_user.id
			@article.destroy
			respond_to do |format|
				format.html{redirect_to :back}
				format.js
			end
		end
	end

	def upvote
		@article.liked_by current_user
		respond_to do |format|
			format.html{ redirect_to :back }
			format.js{}
		end
	end

	def downvote
		@article.unliked_by current_user
		respond_to do |format|
			format.html{ redirect_to :back }
			format.js{}
		end
	end

	private
		def article_params
			params.require(:article).permit(:title,:content,:image)
		end

		def set_blog
			@blog = Blog.find(params[:blog_id])
		end

		def set_article
			@article = Article.find(params[:id])
		end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
.Article{id: article.id,data:{id: article.id}}
  .Article-header
    .row.Article-info
      .col-xs-2
        = image_tag(article.blog.avatar.url("small"),class: 'img-circle')
      .col-xs-9{style: 'margin-left:-4%;'}
        %span.blogname
          = link_to article.blog.name.capitalize,page_path(link: article.blog.link)
        %br
        %span.time_ago= time_ago_in_words(article.created_at)
      .col-xs-1{style: 'text-align:right;padding-right:0%;'}
        - if article.blog.user.id == current_user.id
          .dropdown
            = link_to fa_icon('bars'),'#',data:{toggle: 'dropdown'},class: 'dropdown-toggle'
            %ul.dropdown-menu
              %li= link_to "Destroy Article",'#',remote: true,onclick: "destroyArticle(#{article.id})"
  .Article-body
    -if !article.title.nil?
      %h4= article.title
    %p= article.content
    - if article.image.exists?
      = image_tag(article.image.url(:large),class: 'img-responsive')
  .Article-footer
    .Action-bar
      .row
        .col-xs-6
          - if user_signed_in?
            - if current_user.voted_for? article
              = link_to fa_icon('arrow-down'),downvote_blog_article_path(blog_id: article.blog.id,id: article.id),class: 'btn btn-default'
            - else
              = link_to fa_icon('arrow-up'),upvote_blog_article_path(blog_id: article.blog.id,id: article.id),class: 'btn btn-default'
              = link_to fa_icon('arrow-down'),downvote_blog_article_path(blog_id: article.blog.id,id: article.id),class: 'btn btn-default'
          - else
            = link_to "Sign Up To Vote",new_user_registration_path,class: 'btn btn-warning'
        .col-xs-6{style: 'text-align:right;line-height:2;'}
          %span= fa_icon('arrow-up lg',text: "#{article.get_downvotes.size}")
          %span= fa_icon('comment lg',text: "#{article.comments.count}")
    .Comment-form{style: 'margin-top: 3rem;margin-bottom: -1rem;'}
      = render partial: 'comments/form',locals:{commentable: article}

app/views/articles/_form.html.haml
= simple_form_for([@blog,@article],html:{multipart: 'true',class: 'Article-form'}, :validate => true) do |f|
	= f.error_notification
	.form-group
		= f.input :title,label: false,input_html: {placeholder: 'Title [Optional]'}
	.form-group
		= f.input :content,label: false,input_html: {placeholder: 'Start Writing here...'}
		= f.input :image,label: false,style: 'display:none;'
	%img#blah.img-responsive{src: '#',style: 'margin: 3rem 0;display: none;'}
	.form-actions
		= link_to fa_icon('camera lg',text: "Add Image"),'#',remote: true,class: 'btn btn-primary attach-image-trigger'
		= f.submit "Post to #{@blog.name.capitalize}",class: 'btn btn-success pull-right'

app/views/articles/destroy.js.erb
$('.Article[data-id = <%= @article.id %>]').fadeOut('slow',function(){
	$(this).remove();
});

app/views/articles/new.html.haml
.row
	.col-md-6{style: 'border-right:3px solid #e9e9e9;'}
		%h3 Create Article
		%hr
		= render partial: 'form'
	.col-md-6
		%h3 Important Points
		%hr
		%ul.guidlines
			

			

app/views/articles/show.html.haml
.row
	.col-md-6.col-md-offset-3
		.Article{id: @article.id,data:{id: @article.id}}
			.Article-header
				.row.Article-info
					.col-xs-1.col-sm-1
						= image_tag(@article.blog.avatar.url("small"),class: 'img-circle')
					.col-xs-9.col-sm-9
						%span.blogname
							= link_to @article.blog.name.capitalize,'#'
						%br
						%span.time_ago= time_ago_in_words(@article.created_at)
					.col-xs-2.col-sm-2{style: 'text-align:right;'}
						= link_to fa_icon('bars')
			.Article-body
				-if !@article.title.nil?
					%h4= @article.title
				%p= @article.content
				- if @article.image.exists?
					= image_tag(@article.image.url(:large),class: 'img-rounded img-responsive')
			.Article-footer
				.Action-bar
					.row
						.col-xs-6
							- if user_signed_in?
								- if current_user.voted_for? @article
									= link_to fa_icon('level-down',text:"Upvoted"),'#',remote: true,onclick: "downvote(#{@article.blog.id},#{@article.id})",class: 'btn btn-default'
								- else
									= link_to fa_icon('level-up',text:"Upvote"),'#',remote: true,onclick: "upvote(#{@article.blog.id},#{@article.id})",class: 'btn btn-default'
									= link_to fa_icon('level-down',text:"Downvote"),'#',remote: true,onclick: "downvote(#{@article.blog.id},#{@article.id})",class: 'btn btn-default'
							- else
								= link_to "Sign Up To Vote",new_user_registration_path,class: 'btn btn-warning'

						.col-xs-6{style: 'text-align:right;'}
							%span= fa_icon('level-up lg',text: "#{@article.votes_for.size}")
							%span= fa_icon('comment lg',text: '0')
				.Comment-form
				/ = render partial: 'comments/form',locals:{post: post}