config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  resources :posts do
    member do
      get 'like',   to: 'posts#like',   as: 'like'
      get 'unlike', to: 'posts#unlike', as: 'unlike'
    end
    resources :comments,module: :posts
  end

  resources :blogs do
    resources :articles do
      member do
        get 'upvote', to: 'articles#upvote', as: 'upvote'
        get 'downvote', to: 'articles#downvote', as: 'downvote'
      end
      
    end
    member do
      get 'subscribe',   to: 'blogs#subscribe',   as: 'subscribe'
      get 'unsubscribe', to: 'blogs#unsubscribe', as: 'unsubscribe'
    end
  end

  resources :articles do
    resources :comments,module: :articles
  end

  get 'checkNotification',to: 'notifications#checkCounter',as: 'notification'         #Check notification with AJAX
  get 'i/notifications',to: 'notifications#notifications',as: 'all_notifications'     #Get User's notifications
  delete 'i/notifications/:id/destroy',to: 'notifications#destroy',as: 'delete_notification'      #Delete users notification  000

  get 'users/:username/followers',to: 'pages#followers',as: 'followers'               #Get Users's Followers
  get 'users/:username/followings',to: 'pages#followings',as: 'followings'            #Get Users's Followees

  get 'gettingStarted/1',to: 'informations#bio',as: 'add_bio'
  get 'gettingStarted/2',to: 'informations#interests',as: 'add_interests'
  get 'gettingStarted/3',to: 'informations#avatar',as: 'add_bio_s'
  patch 'gettingStarted/1',to: 'informations#updateBio',as: 'save_bio'

  match 'i/explore',to: 'pages#explore', as: 'explore',via: [:get,:post]
  post 'i/search',to: 'pages#lala',as: 'do_search'
  get 'i/fetch',to: 'pages#fetch', as: 'fetch'
  patch 'i/updateAvatar',to: 'pages#updateAvatar', as: 'update_avatar'
  patch 'i/blogs/:id/updateAvatar',to: 'blogs#updateAvatar', as: 'update_blog_avatar'
  
  get 'dashboard',to: 'pages#dashboard',as: 'dashboard'
  get ':link',to: 'blogs#show', as: 'page'
  get ':link/subscribers',to: 'blogs#getSubscribers', as: 'get_subscribers'
  
  get ':id/follow',to: 'blogs#follow',as: 'follow_user'
  get ':id/unfollow',to: 'blogs#unfollow',as: 'unfollow_user'
  

  get 'users/:username',    to: 'pages#sketchbook', as: 'sketchbook'
  # get 'userCard/:username', to: 'pages#userCard',   as: 'userCard'
  

  post 'blogs/check_availability',to: 'pages#checkData',as: 'checkData'
  post 'users/check_availability',to: 'pages#checkUsername',as: 'checkUsername'
  
  root 'pages#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :blog
	has_many :comments,as: :commentable
	acts_as_votable
	has_attached_file :image, :styles => { :large => "500x500>",:medium => "400x400>",:small => "48x48#"}, :default_url => "/images/:style/default.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :title,:content,presence: true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :articles
  acts_as_followable
  has_attached_file :avatar, :styles => { :large => "128x128#",:medium => "73x73#",:small => "48x48#" ,:thumb => "24x24#" }, :default_url => "/images/:style/default.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :name,:desc,:link, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :professions
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :commentable, polymorphic: true
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :category
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
	has_many :notifications
	acts_as_likeable
	has_attached_file :image, :styles => { :large => "500x500>",:medium => "400x400>",:small => "48x48#"}, :default_url => "/images/:style/default.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :content, presence: true

	def self.updateRank
		@posts = Post.all
		@posts.each do |post|
			@rank = 0.00
			s = post.likers(User).count
			order = Math.log10([s.abs, 1].max)
			if s > 0
				sign = 1  
			elsif s < 0 
				sign = -1
			else
				sign = 0
			end
			td = (post.created_at.to_i - Date.new(1970, 1, 1).to_time.to_i)
			td2 = td.days * 86400 + td.seconds + ((1000000*(td.seconds)).to_f)/1000000
			seconds = td2 - 1134028003
			@rank = (sign * order + seconds / 45000).round(7)
			post.update_attributes(popularity: @rank)
			post.save
		end
	end

end

app/models/profession.rb
class Profession < ActiveRecord::Base
	has_many :users
	belongs_to :category
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        has_many :posts
        has_many :comments
        has_many :notifications
        belongs_to :profession
        has_and_belongs_to_many :interests
        acts_as_liker
        acts_as_voter
        acts_as_followable
        acts_as_follower
        has_attached_file :avatar, :styles => { :large => "128x128#",:medium => "73x73#",:small => "48x48#" ,:thumb => "24x24#" }, :default_url => "/images/:style/default.jpg"
        validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

        def self.find_for_database_authentication(warden_conditions)
          conditions = warden_conditions.dup
          if login = conditions.delete(:login)
            where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
          else
            where(conditions.to_h).first
          end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title InnFact.com
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag 'http://malsup.github.com/jquery.form.js', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar-default.navbar-fixed-top
    .container
      - if request.original_url != 'http://localhost:3000/'
        .navbar-header
          = link_to "InnFact",root_path,class:'navbar-brand'
          %button{type: "button",class: "navbar-toggle collapsed", data:{toggle: "collapse",target: "#navbar-top-collapse"}, aria:{expanded:"false"}}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
      .collapse.navbar-collapse#navbar-top-collapse
        .nav.navbar-nav{style: 'width:50%;'}
          = search_form_for @q,url: explore_path,html:{method: :post,class: 'navbar-form',style: 'border-color:transparent;'} do |f|
            = f.search_field :username_or_email_cont,class: 'form-control',placeholder: "Search"
            = f.submit "Search",class: 'btn btn-default'
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to fa_icon('home lg'),dashboard_path,data:{toggle: "tooltip",placement: "bottom", title: "Dashboard"}
            %li= link_to fa_icon('search lg'),explore_path,data:{toggle: "tooltip",placement: "bottom", title: "Explore"}
            %li
              %a#noticeBell{href: all_notifications_path,data:{toggle: "tooltip",placement: "bottom", title: "Notifications"}}
                = fa_icon('bell lg')
                %span.badge#notification
            %li.dropdown
              = link_to fa_icon('bars',text: 'Navigator'),'#',remote: true,class: 'dropdown-toggle',data:{toggle: 'dropdown'}
              %ul.dropdown-menu
                %li= link_to "Account",edit_user_registration_path
                %li= link_to "Settings"
                %li= link_to "Sign Out",destroy_user_session_path,method: :delete
          -else
            %li= link_to fa_icon('',text: 'Sign In'),new_user_session_path
            %li= link_to fa_icon('',text: 'Register'),new_user_registration_path
  - if !notice.blank?
    .notice
      %p= notice
  - if !alert.blank?
    .alert
      %p= alert
  - if request.original_url == 'http://localhost:3000/'
    = yield
  - else
    .container
      = yield

  - if user_signed_in?
    #newPostModal.modal.fade{role:"dialog"}
      .modal-dialog
        .modal-content{style: 'border-radius: 0;'}
          .modal-header
            %button.close{type: "button",data:{dismiss: "modal"}}
              &times;
            .modal-title
            %h4{style: 'text-align: center;'} Compose Post
          .modal-body{style: 'margin-bottom: 4rem;'}
            = render partial: 'posts/form'
          .model-footer

app/views/layouts/blog.html.haml
!!! 5
%html
%head
  %title InnFact.com
  = stylesheet_link_tag    'blog', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag 'http://malsup.github.com/jquery.form.js', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        = link_to "InnFact",root_path,class:'navbar-brand'
        %button{type: "button",class: "navbar-toggle collapsed", data:{toggle: "collapse",target: "#navbar-top-collapse"}, aria:{expanded:"false"}}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      .collapse.navbar-collapse#navbar-top-collapse
        %ul.nav.navbar-nav.navbar-right
          %li= link_to fa_icon('',text: 'Sign In'),new_user_session_path
          %li= link_to fa_icon('',text: 'Sign Up to Follow'),new_user_registration_path,style: 'border:1px solid;'
  .container
    = yield

app/views/pages/_blog.html.haml
.blogCard{style: 'padding:1rem;margin:2rem auto;box-shadow: 0 0 3px 1px #e8e8e8;'}
	.row
		.col-md-3
			= image_tag(blog.avatar.url(:large),class: 'img-responsive')
		.col-md-6
			%h4= link_to blog.name.capitalize
			%span= blog.category.name
			.Counter{style: 'margin-top:2rem;'}
				= pluralize(blog.followers(User).count,"Follower")
		.col-md-3
			- if user_signed_in?
				- if current_user.follows?(blog) and current_user.id != blog.user.id
					= link_to "Following","#",class: 'btn btn-unfollow',style: 'width:90px;text-align:center;'
				-elsif !current_user.follows?(blog) and current_user.id != blog.user.id
				= link_to "Follow","#",class: 'btn btn-follow',style: 'width:90px;text-align:center;'
			- else
				= link_to "Sign Up To Follow",new_user_registration_path,class: 'btn btn-warning',style: 'width:135px;text-align:center;'
	

app/views/pages/_user.html.haml
.panel.panel-default{style: 'position:relative;width:225px;display:inline-flex;margin:2rem;text-align:center;box-shadow: 0 0 3px 1px #e8e8e8;'}
	.FollowUnfollow{style: 'position:absolute;top:0;right:0;'}
		- if user_signed_in?
			- if current_user.follows?(user) and current_user.id != user.id
				= link_to "Following",unfollow_user_path(user.id),class: 'btn btn-unfollow',style: 'width:90px;text-align:center;'
			-elsif !current_user.follows?(user) and current_user.id != user.id
				= link_to "Follow",follow_user_path(user.id),class: 'btn btn-follow',style: 'width:90px;text-align:center;'
		- else
			= link_to "Sign Up To Follow",new_user_registration_path,class: 'btn btn-warning',style: 'width:135px;text-align:center;'
	.panel-body{style: 'width:100%;margin-left: auto;margin-right: auto;margin-top:3rem;'}
		= image_tag(user.avatar.url(:large),class: 'img-circle',style: 'margin-left:auto;margin-right:auto;display:table-cell;')
		%h4= link_to user.username.capitalize,sketchbook_path(username: user.username),style: 'color: #558EAB;'
		%h5= user.profession.name
		.Stats{style: 'display:block;margin-top:2rem;'}
			.followers-counter{style: 'display:inline-block;float:left;'}
				= user.followers(User).count
				%br
				%span{style: 'font-size:0.8em;'} FOLLOWERS
			.followees-counter{style: 'display:inline-block;float:right;'}
				= user.followees(User).count
				%br
				%span{style: 'font-size:0.8em;'} FOLLOWINGS

app/views/pages/checkData.js.erb
<% if @data.nil? %>
	$('span#user-availability-status').css('display','inline-block').css('background-color','#0F9429');
	$('span#user-availability-status').html("<%= @message %>");
<% else %>
	$('span#user-availability-status').css('display','inline-block').css('background-color','red');
	$('span#user-availability-status').html("<%= @message %>");
<% end %>

app/views/pages/checkNotification.js.erb
$('li#notification').text('<%= @count %>');

app/views/pages/checkUsername.js.erb
<% if @data.nil? %>
	$('input[type="text"]#user_username').css('border','1px solid #0F9429');
	$('span#user-availability-status').css('display','inline-block').css('color','#0F9429').css('margin-top','-1rem').css('margin-bottom','1rem').css('padding','0');
	$('span#user-availability-status').html("<%= @message %>");
<% else %>
	$('input[type="text"]#user_username').css('border','1px solid red');
	$('span#user-availability-status').css('display','inline-block').css('color','#E43E3E').css('margin-top','-1rem').css('margin-bottom','1rem').css('padding','0');
	$('span#user-availability-status').html("<%= @message %>");
<% end %>

app/views/pages/dashboard.html.haml
.row 
	.col-md-6.col-md-offset-3{style: 'text-align:center;'}
		/ %h3= current_user.profession.name
		/ .stats= pluralize(Profession.where(name: current_user.profession.name).all.count,"Member")
		/ %hr	
.row{style: 'margin-top:4rem;'}
	.col-md-6{style: 'border-right:3px solid #e9e9e9;'}
		.Posts#Posts{style: 'width:90%;margin-left:auto;margin-right:auto;margin-top:-2rem;'}
			.Feed-header
				.pull-left{style: 'font-size:1.8em;'}
					Stories
					%button{type: "button", class: "btn btn-info btn-sm",data:{toggle:"modal",target:"#newPostModal"},style: 'border-radius:0px;'}
						= fa_icon('pencil')
				.desc.pull-right{style: 'font-size: 0.8em;background-color: #e9e9e9;padding: 1rem;'} From People You Follow
			.Feed-body#Posts_feed_body{style: 'margin-top:3rem;padding-top:6rem;'}
				= render partial: 'posts/post',collection: @posts
			#loader
				#anime
			= link_to "Load More Posts",'#',remote: true,class: "load_more_dash",onclick: "load_more_dash()",style: 'display: block;text-align: center;background-color: #ffffff;line-height: 3;margin: 3rem auto;box-shadow: 0 0 3px 1px #efeeee;'
	.col-md-6
		.Posts#Posts{style: 'width:90%;margin-left:auto;margin-right:auto;margin-top:-2rem;'}
			.Feed-header
				.pull-left{style: 'font-size:1.8em;'} Popular Now
				.desc.pull-right{style: 'font-size: 0.8em;background-color: #e9e9e9;padding:1rem;'} From Blogs You Follow
			.Feed-body{style: 'margin-top:3rem;padding-top:6rem;'}
				= render partial: 'articles/article', collection: @articles
			#loader
				#anime
			= link_to "Load More Posts",'#',remote: true

app/views/pages/explore.html.haml
.row
	.col-md-3
		%h3 Explore
	.col-md-3.pull-right{style: 'text-align:center;line-height:4;'}
		.blogs-opt{style: 'display:inline-block;padding-right:1rem;'}
			%h5= link_to "Blogs",'#'
		.users-opt{style: 'display:inline-block;border-left: 2px solid #e9e9e9;text-align:right;padding-left:1rem;'}
			%h5= link_to "Users",'#'
%hr{style: 'margin-top:0;'}

.row
	.col-md-10.col-md-offset-1
		- if @users.present?
			= render partial: 'pages/user',collection: @users
		- else
			.Nothing-found{style: 'display:block;width:50%;margin-left:auto;margin-right:auto;text-align:center;color:#848484;'}
				%h4 Ahhhh... This Search Returned Nothing
				= fa_icon('frown-o 2x')

app/views/pages/fetch.js.erb
$('#Posts_feed_body').append('<%= escape_javascript(render(:partial => @posts)) %>');
<% if @posts.empty? %>
	$('a.load_more_dash').attr('data-id','none');
	$('a.load_more_dash').css('display','none');
	$('#loader').hide();
<% end %>
$('#loader').hide();

app/views/pages/followers.html.haml
- if !@users.empty?
	%h3 Followers
	= render partial: 'user',collection: @users
- else
	#Empty{style: 'width:100%;color:#989898;text-align:center;font-size:1.6em;margin-top:10rem;'}
		NOTHING FOUND HERE

app/views/pages/followings.html.haml
- if !@users.empty?
	%h3 Followings
	= render partial: 'user',collection: @users
- else
	#Empty{style: 'width:100%;color:#989898;text-align:center;font-size:1.6em;margin-top:10rem;'}
		NOTHING FOUND HERE

app/views/pages/index.html.haml
#Welcome1{style: 'color:#000000;width:100%;height:100vh;text-align:center;margin-top:3rem;'}
	%h2 InnFact
	%h5{style: "font-family: 'Nunito', sans-serif;"} hangout with people with same passion as yours
	%hr{width: "40%"}
	#Registration{style: 'width:400px;margin-left:auto;margin-right:auto;margin:5rem auto;'}
		= render partial: 'devise/registrations/new'
#Welcome2{style: 'background-color:rgba(206, 182, 210, 0.97);padding:3rem 1rem;color:#ffffff;width:100%;height:100vh;text-align:center;'}
	%h2 FAQ's
	%hr{width:"40%"}

	#QA{style: 'text-align:left;width:80%;margin-left:auto;margin-right:auto;margin-top:5rem;'}
		%h3.Q What is InnFact?
		%p.A InnFact is a community website where you can meet with the people with same field of interest so you can share better oppotunities.
		



/ rgba(181, 58, 58, 0.97);
/ rgba(71, 165, 72, 0.97);
/ rgba(71, 129, 165, 0.97);

app/views/pages/sketchbook.html.haml
.row#body{style: 'margin-top:3rem;'}
  .col-md-3.hidden-sm.hidden-xs{style: 'text-align:center;'}
    .userAvatar{style: 'position:relative;'}
      = image_tag(@user.avatar.url(:large),class: 'img-rounded',id: 'userAvatar',style: 'border: 1px solid #e9e9e9;position:relative;',data:{toggle: "tooltip",placement: "top", title: "#{@user.username.capitalize}"})
      - if user_signed_in? and @user.username == current_user.username
        %span= link_to fa_icon('camera lg'),'#',remote: true,onclick: "update_avatar()",class: 'update-avatar-trigger',data:{toggle: "tooltip",placement: "bottom", title: "Change Avatar"}
        = form_for @user,url: update_avatar_path, html:{remote: true,class: 'update-avatar',method: :patch,multipart: true} do |f|
          = f.file_field :avatar
          = f.submit "Upload"
    %h4= link_to @user.username.capitalize
    %table.table{style: 'margin-top:3rem;'}
      %tr 
        %td 
          %b Is
        %td= @user.profession.name
      %tr
        %td 
          %b From
        %td= fa_icon('map-marker',text: "India")
      %tr  
        %td 
          %b Joined
        %td= fa_icon('clock-o',text:"Jan 2015")

  .col-md-6{style: 'border-left:2px solid #e9e9e9;min-height:100vh;border-right:2px solid #e9e9e9;'}
    - if @posts.blank?
      .EmptyDiv{style: 'text-align:center;color:#989898;font-size:1.1em;'}
        - if user_signed_in? and @user.username==current_user.username
          %h4
            #{fa_icon('frown-o lg')} Nothing to show here  
          = link_to "Compose Post",new_post_path,style: {color: '#989898'}
        - else
          %h4
            #{fa_icon('frown-o lg')} Nothing to show here 
    - else
      .Posts#Posts{style: 'width:90%;margin-left:auto;margin-right:auto;margin-top:-2rem;'}
        .InFo{style: 'display:block;background-color:#ffffff;box-shadow:0 0 3px 1px #efeeee;padding:1rem;text-transform:uppercase;'}
          .FoLlowers{style: 'text-align:center;display:inline-block;width:49%;'}
            = link_to pluralize(@user.followers(User).count,"Follower"),followers_path(username: @user.username),data:{toggle: "tooltip",placement: "bottom", title: "Followers"}
          .FoLlowings{style: 'text-align:center;display:inline-block;width:49%;border-left:2px solid #e9e9e9;'}
            = link_to pluralize(@user.followees(User).count,"Following"),followings_path(username: @user.username),data:{toggle: "tooltip",placement: "bottom", title: "Followings"}
        = render partial: 'posts/post',collection: @posts
        #loader
          #anime
        = link_to "Load More Posts",'#',remote: true,class: 'load-more-profile',data:{id: @user.username}
  .col-md-3.hidden-sm.hidden-xs
    .Follow-field{style: 'margin-bottom:3rem;'}
      - if user_signed_in?
        - if current_user.follows?(@user) and current_user.id != @user.id
          = link_to "Following","#",onclick: "unfollow(#{@user.id})",remote: true,class: 'btn btn-unfollow',data:{id: @user.id}
        -elsif !current_user.follows?(@user) and current_user.id != @user.id
          = link_to "Follow","#",onclick: "follow(#{@user.id})",remote: true,class: 'btn btn-follow',data:{id: @user.id}
        -elsif @user.id == current_user.id
          = link_to "New Post",new_post_path,class: 'new-post-btn',data:{toggle: "tooltip",placement: "bottom", title: "Compose Post"}
      - else
        = link_to "Sign Up To Follow #{@user.username.capitalize}",new_user_registration_path,class: 'btn btn-warning'

app/views/pages/updateAvatar.js.erb
$('img[id = userAvatar]').attr('src','<%= @user.avatar.url(:large) %>');